---
kubernetes:
  children:
    master:
      hosts:
        k3s-0:
          ansible_host: 192.168.86.75
        k3s-1:
          ansible_host: 192.168.86.76
        k3s-2:
          ansible_host: 192.168.86.77
        k3s-3:
          ansible_host: 192.168.86.81
    worker:
      hosts:
        k3s-4:
          ansible_host: 192.168.86.82
        k3s-5:
          ansible_host: 192.168.86.83
        k3s-6:
          ansible_host: 192.168.86.84
