# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:/xBBzIlajW+hk+MlLfoZ/9XYMHgT5fY=,iv:zg1U46pToT4ZKe7QJVZBI2pHaYhMmyyOF1PJEmhbDrI=,tag:RDvmGjJjRtS9hHPb6n4WFQ==,type:str]
    api-key: ENC[AES256_GCM,data:5bs12GK40eS+5kFjOL1BJI9QkV0H7R2ErHITQBsmqhkntIQlOA==,iv:r68cxHcC6dMX1OXHURhcw3q4xN9Aik+wetvTN2URZYI=,tag:q6p2rhbfFz/nAIeUwd19Ng==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTTjd4enN0cWpvZFM3dzZt
            VWdvTHlnaE1xTlJtODFzb0trQVFNT2FrK0ZrCmlEVlBLa0xUWHhVUkZyb256a2ho
            UERKcWQ0Ny9uNGl6clBDRS80VStkUXcKLS0tIEd4ZlRpcGI5WnVGY3owQmRwdTlZ
            anNBclV1TFJrVElxTk5qZDFVSEJWMUkKpIGd9j+/RSWNNx1wBkm7jcTCNL8CkgwJ
            p5UYYptjURTrm9o8E84mfxmAXdK8xwK991vKyR/sfkdeSPrXgn7fUg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T21:33:14Z"
    mac: ENC[AES256_GCM,data:z66GsRJn7cT1q+0xWwuizc+EJFg2n+jZsh56bLWAOqrkQ5sj9BS667FpXgRSFqE1HulWcq53Xm9FztdEW78u1oweddIOyoaDj4Ch4EcSb+cXE+0yVPydPCjw3dsP6AyDHbC4Y1O05LfsbfIIclSmYwp7JoZV28u24fbPVpm/Dn4=,iv:RaoorOvzrow7ODotBvxwKJJwkKqnNrXdYAuO0PwBxPg=,tag:oQJ8p5oZwsrpeLGulIy9mA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
