# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: external-dns-cloud-credentials
    namespace: networking
stringData:
    email: ENC[AES256_GCM,data:0rQMhkVXdwSlpYw7v6E4VjRHrUSsu6c=,iv:qGjyxgjJ3jBV/d5+ga6+MbGubehHiIdbjwCHxN3HbAo=,tag:nNrhlJ7wxpRgDwjxUHCYCA==,type:str]
    api-key: ENC[AES256_GCM,data:oT+hll095UQburtQ5JBvSRqaQzi/Kj4L9GhM3/tX7tw+JcTrPA==,iv:ONgYK+M8x7RgH96DOfw20mfJaq67vEF7psYKGqr3aZU=,tag:qhrWP4+fR+G2ECbVAExmEw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB5eTVXT2llakdqemJ1dUEy
            ajBRNzlSMUNPZ292RW5aUDBrZjV5bFZzNHlRCkduVnMvSE1NYTMvUTA4L0poZU9W
            YW1OeEF4SnFsc1dyUS9heEk0TThheXcKLS0tIEx5K1IvYm5lL3RCV2xtSnJjZDB5
            czBQZGpiMWdRK0g1ZzdEWGhLajVRUDAK3KxkzOqKYd2EWL1fGWvo55x7h7jLNSZu
            cQhjLc5je3vVIpMhewXBlUJRPflZ0KQ8MEjgDPTZVsxXmpQ9vFdWCQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T21:08:28Z"
    mac: ENC[AES256_GCM,data:pdr6EEnN2qXdxMNMSfsM2HEoBF1JG0M6/Xx8xwyKPAMNpS7ywip3hEzE+e2HxQ4nty2W3J9hScngynNU+7M8lDG5HGuTX93qFGgbFzTfcDeM6frJX5/6sxqhvjxBhwi6EBNSeapBm3en0Uq7N/HqJueE/CkWS7LqpQzGzgb66AY=,iv:LIFct+gwWhodnD0pEhcRcbqd285IOpPG15Si7JIjDa4=,tag:TXV5UyXjQrkrSEm9dSY8yg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
