---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-settings
  namespace: flux-system
data:
  TIMEZONE: America/Denver
  METALLB_LB_RANGE: 192.168.86.100-192.168.86.125
  METALLB_K8S_GATEWAY_ADDR: 192.168.86.100
  METALLB_TRAEFIK_ADDR: 192.168.86.101
