# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:xz9P5c8ud3vMry8xQv6qzXgWIw==,iv:cPR9IYX1+8/ghZUG9eKZuZyknCthk3DCeLgWQintHg4=,tag:0Wdy+13AILDvIGwOB2TtiQ==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:N4YBTmCIhFBB7ey6o/H8qqXIYzH8nCA=,iv:1K7iVPjQRPUeBL6VDy1Ni1/eAt/D1sHSAw/BYAUII+0=,tag:W1m2AuLuvF0zptGMThBblA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTRkhLcmxQU0ZycHBJa0dn
            c2RUcklMNFd0aWIzLzF6OFp5QUhzb25XYUM4ClZTaFFjVnk1TExrYnhzZndhb3g5
            SDNIcjkxK2IvUWI5YlFZNkdydHIvdGMKLS0tIFo1dndmV1plNnlrQVZPQkxxM2k4
            dmhxeUoyV3hiQ2NJTms5M0YrU0tiRmsKakF1VtRcToi1yo+hqxywrtSHjF4Ozliz
            YJHhuHFUK80+tzbxqEcseZxOz+C0pqxP4xCma88O/CQBfluq+Y1OsA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T23:36:47Z"
    mac: ENC[AES256_GCM,data:JC5SHw42R9l5bQHM0qfpXwWNWERw7IxQPeJZ5PtPGaoy7751itQ3PcdyLg4+oRq+SviAaQsr6FTQcz797hikwmIp07ek32EGWbW45nBh3/0toPrBMimU7aSQX7Fh/YEF2jP/0nz/JeaLWtZ0rKtEfvHbsc2T9Ds1ZEp8T8+Mfwk=,iv:AuaO1KivLfCRBntcx1mWsp9d/I4NkqZqrMviEdHX3TQ=,tag:2Nft9Lw/FCgMJOC9cp40YA==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
