kind: Secret
ansible_user: ENC[AES256_GCM,data:O1PGIVyCND1XlA==,iv:aDZeNC6Alcgyk/QHeH3EfPiQ7vuw8twzKFgy31TUlYM=,tag:Kn0WhmdA+/d3ajY+Di2CaA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:kOCzKa3ACAA=,iv:HFJQ/Ci4k7cundCp7sBrY3ts14nitnuk+b4UPkPjz9U=,tag:nswEJjvpPZBx4uM/gK34+A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiaGpPWk9Mbm5GejRxdlV4
            bWJQY3RsY3dINStwQjh0VWl6NmRvZ2hqU3lVCmF6Q2xtSFlUeHJWZms0eCtVQ3pr
            VjV6cmdyV1NMWFlicmtPWjJzQ1dKM3cKLS0tIFdibGRHNm8wSUhLYTFJV0dtRlVk
            Mm1rMmZhbnBZRFZSWmVYUEY0RHB0aWsK/Q728gDkGuqmZhVmiOKofpIKsBphcpMv
            PRqr8MyWHQAoS58w1rk1NTuik03x7OxHi9Ni4984t0HIjoZSpMBuDA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T19:37:24Z"
    mac: ENC[AES256_GCM,data:SjgarJN4O3PGEyfDDBUtvIVY5zmYtVPsmq9ASMIK7dTMSFcSnhS1ynFoRadO6nQc4VsQMVjQyyaik7Ftay1gkf/Gx5yznBq2ACWvr28/Sy3IIqqPbDmWQ42n2ooIeAmNKsmC6/I7R7FjtV2KLdMMIiqfKbPAQdCM1Pstk4JYMnM=,iv:YjN6/q7PhpjdBNAR5sXOwBILTHKJXv3Tg2QzGmAfOBg=,tag:aMtVt6Q+Puh6zByTETy9EQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
