kind: Secret
ansible_user: ENC[AES256_GCM,data:z/qmpJ0oL4vT+A==,iv:ummWfunQ9XIkbplH7b2uyujs5+1eY0fuxCMwEAKtys0=,tag:73CRTLx2fuivynHKGMUfXA==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:jIPQD9wK/SM=,iv:QjDECqaTjAXagOUl7m8oHxIdM1kpbIXOGKW1WQBqkKI=,tag:V5Eh0dxnVey8Kn42jbRGkQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHN0U0czBQQWM3aHpCWW1W
            R04wMkJMK01QclY5M3lWSDZhWmxsQkNXZlZBCnNZVmNoSkJ5NVJaZndFcEtaZGRJ
            ckUzeTIwWGwvNU4zZHRzWTdsSkZBaXcKLS0tIHVYVExLZ2FzaFZqYkM2bmZ2NlZk
            aGU5Qkowb1RjK1dSbkRMOHMvZDdVeVkKvc4NNRn4s/3X9pxxA5LDCt+mmrSSpViN
            VclCZ7mn+iRm+iyqzZEmqvJcW8SPjwe8ug4AMddPUAczHLoz7WsCyA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T23:36:47Z"
    mac: ENC[AES256_GCM,data:149ucGvYwW9G+0vJlXYxZKpBkGUPNwB5FaT6EWVxD5nPrfbbQKmtg1JhjAIecD7s0XkSMCMT6SjOzsDhbCfSZcLjAeQEdO6teFxaXUgbRYniom3YrjO4aK03+7h/wauRaAUc4so5klr89P5leCdb7bKfirUcST/Zei10u3WKJ/I=,iv:6QZ/G783etslTCM0LLCxxn15mLy5/DenN3dGVJVFQ+Q=,tag:muuX5LTvuTQSVvYol9JUKQ==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
