kind: Secret
ansible_user: ENC[AES256_GCM,data:ME1OJgFxANgNRQ==,iv:si0ckjK/9xbmYux3MCOOUQBltUdWdjjDs3y9xZKuu24=,tag:Kko7Cq5iQsy8g5yF/ykNKw==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:P+Gllft2vVs=,iv:kVO8uEbo1fXVoBA727UiK43pKWJ0Rx/DixKqIsyj58c=,tag:zfSeqDY9hs5tn1pNKPRbAA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSK3I0bUdHeWY3NEdjeFpS
            cWUzWS9nZWdPcVlta2gwQ3p4VHJzSDRzQ2w4CnJJQUg3cmFSSDMzV1hFTTIzSTl4
            dXhnMXdDZlVwdjZPMGdscThuTFBqQUkKLS0tIDF5WXllZWNYNHluYU45QU93ZWNu
            bmFMb0x3KzhFcGhwSWFtd2FPempjQm8K6SW3czh+LI91w63RInRlNztae4s+KkG3
            PzBpe/YBFX1267wdMEbzrA+o9FnUbgAC3opBom/4EBuxqrWwv7hx8w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T20:45:38Z"
    mac: ENC[AES256_GCM,data:n+IsoL154a4A376pNBJdZvU/y2K4OGJ/iZEFqZXUHrD+0oGWPG/AYAxn/AtBolUIlS2K567ufbSsNp7bSrOLzSo234w46wd0MeNZSYlLbBaLxB+msZR+FFpiHWZBKusdC+f7X6bbE5EoQy/aD9bdW9HFzNnG8Ih8XzNxung2LKc=,iv:urUKB/NVCuOAqAyHKLPKcfbtzDnPP4ISs44ri7GcogY=,tag:D/+9/cWAtrzsd+1NMF02UA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
