kind: Secret
ansible_user: ENC[AES256_GCM,data:KWxkc5820iqScw==,iv:D/eO/W5Y5kex9oxkN59l/mQcrFVkFTV+mfLIwOjuIIQ=,tag:moYRfQs2XY7LsXSFcRrqvQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:RSkieQLK7J8=,iv:WPJXeiB0lxBD0yyfvUzMMMP4EndSrI5Kp2I7xu2EPcE=,tag:86Qo3T0WSv5eZdlz9QE08Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzVEswQnQreUVmbCtyUDBu
            SjFUQXMwbXdyLzdpdHpIQmlhdXhueEVuZXdVCjdpTHlBWHNYZ2VFVUNMWjFsVDAr
            SUI0bVZ0b2tsZVZIcTFzZDBrRjN3SGMKLS0tIHB3SWZ4U0tING5HZlZwRlVWMy84
            aG5HdFN2UWt5SFlkYkpLcHZZRGZjV2sKQ/cOA07x6CXCvLzA0EYnj7jOdg1IDdqh
            aYlYmlokidagOWY1xdURroHhLD/8PHLHHlfKXJzr/EpVMhytd86E0Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T21:33:14Z"
    mac: ENC[AES256_GCM,data:qYU9gcorOSWXDfQrXoBZWD2CARq5mZ7qe5JpMXgKR+8lQdP+YfLxrPLsAKrpV1pn6iSGn/BrUDdvF0Xl/gXN9FG7VruuGgLozoFgBJ/vSpASfEgZILt1MEJM8ugRTrVHB/brC7bvlpc9473egiSCvMqddYg1FXDTehgCQdkZ1mA=,iv:ofSLhtsgIfigR2H7TxKuOq/93Rfa/8T16KGqBOQRTjQ=,tag:TcptDVcQbol8sQA53XrZcA==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
