kind: Secret
ansible_user: ENC[AES256_GCM,data:1QewGGWmhWuX9g==,iv:9ASBsMMsUYOBiweizMTEC1UkKA6zjshJwFR8He9Fe9A=,tag:MTgdo53U6nLacoyARl+n5Q==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:Tl4PD9GsbUc=,iv:ZpAaYE7qfB5+Ca0TKP6Lsu8nnEX9048ga9Zjt9D9Rdc=,tag:MMWM4Wlc1mTLOgoYYFziLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCK3FLMktoQWxOL3lZZjN6
            OE9DSUc5NENTMU9CVEJubU9KQm9PTlBlWlFBCkY1aTBUb05FWkNIN09ZZEVDbEE5
            b1VtSTAyMDN5M2l0Qnk2QUJTRDhnaFUKLS0tIDlPeERRRmFBL0o5SVhORWh1c1Zx
            b2tpcmljdzRzVVlxeDJqNG1XdjdQOFEKaiduua6QIXFrJHxiGeVB9SzgOc4ieCa+
            WkHyFefoYC43KClEE45G1/BmaH6k3sKgDI5qKShJ/iijHyTFt3io1g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T23:36:48Z"
    mac: ENC[AES256_GCM,data:A1MQsnIpennHQ9QBHsudCxA2GBy7eVYbjuMl/AYEPdiRvxQzxf0h0iQhn3GTv1jVzjUTcL8EWEcNKKqqDMgEQL6LyC3c0HYQOP2XVwJeLY/SKkb0KqN+x7j4B+6gl9cUL5CNZOxhtE8Rn2AmTa2dP+Yus/IhJhBe2VkrvO+NtfM=,iv:ExIyP0aLeNfiXBVT9jCED+XXjwRMdG3Ot6YOlQWxlFc=,tag:KKSnmDg0Y9NKbnL06hWU9A==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
