kind: Secret
ansible_user: ENC[AES256_GCM,data:clCIa7GTgu2Gzg==,iv:Fi8JG5GbGd+aonnehuRfvm1F4CMy7Jl3d/t7+LEU3vo=,tag:wO9H92jZ6Z2C9AxBYYcKZQ==,type:str]
ansible_become_pass: ENC[AES256_GCM,data:t3/icG2cA68=,iv:uJA0eCLwbHVZbWWkMlyUS8Q3Q6x1V0DeJ1DfrtBlGjY=,tag:ymv7dqYzr/FiEjF7zHUAGQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0Y3B6RUwwRmdlWDdCUUFI
            WGxEV1M2dXYwQ1hLMllnNE0rMERXKzZ1UkVzCjY5ZTEwL01EN2ZxTUZlSDhFOTRN
            SXFIcmQzMDkvV21sR3prcnZGTlM4elkKLS0tIEtxNm1VVysxZ3Rtb1NTbS9sVDFn
            Y2Z1YmVoRXdpc1hINng2eXZqTUJDaG8KCGxSuWj7fZiawDUHW7e8tqIAULlvDaDp
            Hax4q/eSBcz9aS9I6iR6plkYDCFRtwQzcUKw6ZazMtGA5rDMIYoRYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T23:36:48Z"
    mac: ENC[AES256_GCM,data:6nqB6HEYFyzZC43LjqLiGriyHUN1makL2CdZovjnNNZfR4p2/+zKaQ6ZrVpFVClkqqkKbGtI8Q/LfnEsNOofymCv3KwKOE4CjPC5Oq0UBHlJbuzMRAtGl431HBqXqP3KWweYO52G0KLcvQym8V2Omh4vOAqYvWk7nDQeb6EgvCI=,iv:/NXii7M3CjHdtohOKASa9D++v+3YGk9Yj+aS6guoRLQ=,tag:uYAJMZi34n+exQk117Xepw==,type:str]
    pgp: []
    unencrypted_regex: ^(kind)$
    version: 3.7.3
