# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:2M1pSz8vwiQvnrkN4X2B7hGrFjgGWV0qjuU+xE62is7jo+mBUw==,iv:/pub53y6Otg+XARA9A1goRpklFHlyWWp2om65nJx018=,tag:COwkHn6yXPyygqZGux2mnQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5UWlVdEtaRnpIT2prUUNG
            TllUNi8yYnoxR0pEWHdrdGV4L2FJZzhiS0RvCkFNbU5BL1hLb3dRSnN6T1BjZEtG
            ZmRpdy9KelpNMGVoSC91blI3NWdIV2MKLS0tIEFtYy80WTlqRENzUGYzTXg3aitV
            WVNBK1RsaHR3clhtdTdKdUpQYVpINlEKMammATvtPFjNuuGWd6cZAbREpH/wb4uA
            Tlum5wwuPLIYJ412zbiQzNCvTnxacNZS5OdvgzSu7yewFYy4wPU1RQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-05T19:37:24Z"
    mac: ENC[AES256_GCM,data:cnLK1hqZusiXEblTHLR+CFwDfvQ/M0mwSQ4tUz90QmQBofwQy6DyFIkSQurfGKuJ5V8rt4ofm8Boc3+zTs4xgwIH88uizu8aiKuoTEm5Czjge6OSpLgh0SHaPllh23tE+J/4gQMjBk5pkWT2dUB0dFFJNCmp2kMXVCNX+bZB7CY=,iv:q2X2rG/naE+pydAWxQNPLof2tKIMpYyoTXjtTQlSBg4=,tag:K0uHEVVwC0m7t5V/MYE2aw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
