# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:vUfa6rh0LXOs0/BsZwOnco2OKRmc09dHpXNOfQt4ulNpOGYRNA==,iv:NYDEYZAeqzYGXO3Ntfr4c2O1hnqdtBJWaXthVhgFZow=,tag:iBXFqCwyzi9frvMW0qzUPg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTWTNIVFhUSmpjRVZVQ3dQ
            d3Y1K2hxMU0rTmk3bGU0T1A1eUh0UnBmSW1FCnpFbllRa1EwWU52d0tJZUx4ZUFu
            bC9FVlRPK3o1WUhlYUNJN0l0dUNTNHMKLS0tIFllY0tzVHhNTG0vdXpNTlk0NG5L
            RTQwdTJJSWY2b25BWFZKZVgwaU0vOWMKfkpzRfs3x3sszIk6+pU98c2icbpYthOU
            BA8rYmMJaEkD5qZJaXBwyn1QoUdICDCJE1Ol6p4XZSfjPtKke/ZfHw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T01:04:00Z"
    mac: ENC[AES256_GCM,data:XYtfNGKlsWpJlynvL8pdRq6K67IBjZ22GqphZtA+Wyzv/Y2t082yaCXoXW45E29CqBepVxITr4kYPxLsPXPg7jmI+Qn0nSmVniC0Q7cpNY0cqkJ6J1Oj+k6+hSkOc3U2drw78uQDe0hj+tYQAU9zxNZ/jfp9UMd43IRUHhwWa9Q=,iv:poH66aFTH0wmWikeYEIWl8wt2CeW66RrLPkHiKwYRmk=,tag:NtyOk9q0Mytux/VAIGYrwg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
