# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:95Kkx7O8YCCiGUzo/Lhpii93hT8K0wetYX/D55vMoaN5gR/oZQ==,iv:B2dSV3zGyCj2X4hXdUR+qC4Ti+pCBKr4yIjIsXjXzAc=,tag:iWlDjHLeKgH30KZSHlV0NQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1vzragh0nwvt3r94fshvxnc8s7yttw7wg4yz0793sts2arwvxap7sjcvn4d
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzMDB3MndqN1BBRllrQ3lm
            THJPZi80SW8ydWsvU3hBM1R4K2VNNXFhNjM0Cld5endubnhXY2NoMnpsMTlBaXFO
            S21obHNvbzVTQVpIcGVMZGpPbjZTZ0kKLS0tIEVrd2VwOWY0Q003ZDRGUk96ampz
            OUxsSmtKMTBQS2ZNcXhqdUpXQmZOS0EKqOzqMWfByzlSJ2vVC40Nqcp6Gbe/RIjl
            RoEIslTUKQAf32cjw6ZfGBk19PjaZXAx0XThuHX77DKhClf+egBgIA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-10-06T21:08:28Z"
    mac: ENC[AES256_GCM,data:aYvDsIvM5HaAI/o1lyqihIP4fBCCVvODajWQECTborzz55VckEUs4UutBwdWFd2nB/4LcKE9tDSzp7Yvmz4VLMLLFp7MLcIigaaxo4gn3EQWAXvpXDduE6AOCxNfb+quJ3Imp/VqVCDqa2C+NXB0+Fa6YQclKFbi/8/6pAn8xq4=,iv:KRteXWu6D7GxZJLRgOAkms+uk8JB1CtsI9WUc9GfyjM=,tag:Yshuot4HVPeaJUB2aNmWJQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
